name: Daily Content Update

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  actions: read

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch and process news
        run: |
          # Create a Node.js script to run the content fetcher
          cat > scripts/update-content.js << 'EOL'
          const { fetchAndProcessNews } = require('../src/lib/content-fetcher');
          
          async function main() {
            console.log('Starting content update...');
            await fetchAndProcessNews();
            console.log('Content update completed!');
          }
          
          main().catch(error => {
            console.error('Error updating content:', error);
            process.exit(1);
          });
          EOL
          
          # Run the script
          node scripts/update-content.js
      
      - name: Commit and push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add content/posts/
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No new content to commit"
          else
            git commit -m "Auto-update: Add new AI & automation content $(date +'%Y-%m-%d')"
            git push origin main
          fi